/* eslint no-magic-numbers: 0 */

module.exports = {
  letters: 'abcdefghijklmnopqrstuvwxyz'.split(''),
  attemptsCount: 6,
  levelCount: 5,
  vocabulary: [
    'bear',
    'beaver',
    'chimpanzee',
    'crocodile',
    'dolphin',
    'duck',
    'elephant',
    'fish',
    'flea',
    'fleming',
    'giraffe',
    'hare',
    'hedgehog',
    'hippo',
    'horse',
    'hyena',
    'lion',
    'lizard',
    'monkey',
    'mouse',
    'neck',
    'orangutan',
    'panther',
    'parrot',
    'pelican',
    'penguin',
    'puma',
    'rabbit',
    'rhinoceros',
    'seal',
    'snail',
    'snake',
    'stork',
    'swallow',
    'swan',
    'tiger',
    'turtle',
    'unicorn',
    'whale',
    'zebra'
  ]
};
